import PushNotification from "react-native-push-notification";

export var notifyUpdateResult = message => {
  PushNotification.localNotification({
    /* Android Only Properties */
    id: "0", // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    ticker: "Time is coming!", // (optional)
    autoCancel: true, // (optional) default: true
    smallIcon: "ic_small", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    bigText: message, // (optional) default: "message" prop
    color: "green", // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    tag: "some_tag", // (optional) add tag to message
    group: "group", // (optional) add group to message
    ongoing: false, // (optional) set whether this is an "ongoing" notification
    priority: "high", // (optional) set notification priority, default: high
    visibility: "private", // (optional) set notification visibility, default: private
    importance: "high", // (optional) set notification importance, default: high

    /* iOS and Android properties */
    title: "Daily update result", // (optional)
    message: message, // (required)
    playSound: false, // (optional) default: true
    soundName: "default", // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    number: "10" // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    // repeatType: "day", // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
  });
};
